"""Финансы navbarining legacy va A2 forma inventorysi."""

from tests.smoke.test_forms.inventory.constants import OPERATIONAL_PLACEHOLDER


OPERATIONAL_DIRECT_FORMS = [
    {
        "menu_column": "Основное",
        "menu_item": "Кассовые документы",
        "path": "anor/mkcs/cash/operation_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "path": "anor/mkcs/bank/operation_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Документы чековой книжки",
        "path": "anor/mkcs/checkbook/operation_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Платежные поручения",
        "path": "anor/mkcs/bank/appointment_list+expense",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Платежные требования",
        "path": "anor/mkcs/bank/appointment_list+income",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Ручные операции",
        "path": "anor/mku/operation/operation_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Переоценки валют",
        "path": "anor/mku/revaluation_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Уставный капитал",
        "path": "anor/mku/authorized_capital/authorized_capital_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Взаиморасчеты",
        "path": "anor/mku/offset/offset_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Перекидка аванса клиентов / поставщиков",
        "path": "anor/mku/reallocation_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Оплаты от клиентов",
        "path": "trade/tcs/cashin_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Оплаты поставщикам",
        "path": "trade/tcs/cashout_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Запросы об оплате",
        "path": "trade/tcs/request_list",
    },
    {
        "menu_column": "Денежный поток",
        "menu_item": "Мои заявки",
        "path": "anor/mkcs/request/request_list",
    },
    {
        "menu_column": "Денежный поток",
        "menu_item": "Согласование",
        "path": "anor/mkcs/request/approve_list",
    },
    {
        "menu_column": "Денежный поток",
        "menu_item": "Оплаты",
        "path": "anor/mkcs/request/payment_list",
    },
    {
        "menu_column": "Денежный поток",
        "menu_item": "Документооборот",
        "path": "anor/mrf/sign_document_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Валюты",
        "path": "anor/mk/currency_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "План счетов",
        "path": "anor/mk/coa_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Виды операций",
        "path": "anor/mkcs/cashflow_reason_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Договоры",
        "path": "anor/mkf/contract_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Статьи доходов",
        "path": "anor/mkr/income_article_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Статьи расходов",
        "path": "anor/mkr/expense_article_list",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Дашборд по финансам",
        "path": "trade/rep/finance_dashboard",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Конструктор отчетов по финансам",
        "path": "anor/rep/mbi/mkcs/operation",
        "shell": "a2",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Акт-сверки",
        "path": "anor/rep/mkr/reconciliation_acts",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Оборотно-сальдовая ведомость",
        "path": "anor/rep/mkr/osv",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Оборотно-сальдовая ведомость(BETA)",
        "path": "anor/rep/mkr/osv_beta",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Оборотно-сальдовая ведомость по счету",
        "path": "anor/rep/mkr/osv_by_coa",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Проводки счетов",
        "path": "anor/rep/mkr/transactions",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Карточка счета",
        "path": "anor/rep/mkr/coa_card",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Анализ счета",
        "path": "anor/rep/mkr/coa_analysis",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Прибыль и убыток (PnL)",
        "path": "anor/rep/mkr/profit_and_loss",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Отчет о прибылях и убытках (БЕТА)",
        "path": "anor/rep/mkr/profit_and_loss_two",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Отчет о прибылях и убытках",
        "path": "anor/rep/mkr/pnl",
        "shell": "a2",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Отчет о движении денежных средств (БЕТА)",
        "path": "anor/rep/mkr/statement_of_cashflows",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Денежный поток",
        "path": "anor/rep/mkcs/cashflow",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Оплаты",
        "path": "anor/rep/mkcs/payment",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Отчет по должникам",
        "path": "anor/rep/mdeal/offset/debtor_clients",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Обороты по контрагентам",
        "title": "Обороты по контрагентам(6006)",
        "path": "anor/rep/person_turnovers",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Бухгалтерский баланс",
        "path": "anor/rep/mku/balance_sheet",
        "shell": "a2",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Журнал документов",
        "path": "anor/rep/mkr/journal_list",
    },
]


OPERATIONAL_PAGE_LINK_FORMS = [
    {
        "menu_column": "Основное",
        "menu_item": "Кассовые документы",
        "page_links": ["Кассы"],
        "path": "anor/mkcs/cashbox_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Кассовые документы",
        "page_links": ["Кассы", "Кассовые документы"],
        "path": "anor/mkcs/cash/operation_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Кассовые документы",
        "page_links": ["Кассы", "Денежные переводы"],
        "path": "anor/mkcs/transfer_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Кассовые документы",
        "page_links": ["Кассы", "Денежные переводы", "Кассовые документы"],
        "path": "anor/mkcs/cash/operation_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Кассовые документы",
        "page_links": ["Кассы", "Денежные переводы", "Конвертация валют"],
        "path": "anor/mkcs/exchange_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Кассовые документы",
        "page_links": ["Кассы", "Денежные переводы", "Конвертация валют", "Кассовые документы"],
        "path": "anor/mkcs/cash/operation_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Кассовые документы",
        "page_links": ["Кассы", "Денежные переводы", "Конвертация валют", "Денежные переводы"],
        "path": "anor/mkcs/transfer_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Кассовые документы",
        "page_links": ["Кассы", "Денежные переводы", "Конвертация валют", "Кассы"],
        "path": "anor/mkcs/cashbox_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Кассовые документы",
        "page_links": ["Кассы", "Денежные переводы", "Кассы"],
        "path": "anor/mkcs/cashbox_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Кассовые документы",
        "page_links": ["Кассы", "Конвертация валют"],
        "path": "anor/mkcs/exchange_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Кассовые документы",
        "page_links": ["Конвертация валют"],
        "path": "anor/mkcs/exchange_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Кассовые документы",
        "page_links": ["Денежные переводы"],
        "path": "anor/mkcs/transfer_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Кассовые документы",
        "page_links": ["Статьи доходов"],
        "path": "anor/mkr/income_article_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Кассовые документы",
        "page_links": ["Статьи расходов"],
        "path": "anor/mkr/expense_article_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Кассовые документы",
        "page_links": ["Переоценки валют"],
        "path": "anor/mku/revaluation_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Банки"],
        "path": "anor/mkcs/bank_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Денежные переводы"],
        "path": "anor/mkcs/transfer_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Денежные переводы", "Кассовые документы"],
        "path": "anor/mkcs/cash/operation_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Денежные переводы", "Кассовые документы", "Кассы"],
        "path": "anor/mkcs/cashbox_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Денежные переводы", "Кассовые документы", "Кассы", "Кассовые документы"],
        "path": "anor/mkcs/cash/operation_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Денежные переводы", "Кассовые документы", "Кассы", "Денежные переводы"],
        "path": "anor/mkcs/transfer_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Денежные переводы", "Кассовые документы", "Кассы", "Конвертация валют"],
        "path": "anor/mkcs/exchange_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Денежные переводы", "Кассовые документы", "Кассы", "Конвертация валют", "Кассовые документы"],
        "path": "anor/mkcs/cash/operation_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Денежные переводы", "Кассовые документы", "Кассы", "Конвертация валют", "Денежные переводы"],
        "path": "anor/mkcs/transfer_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Денежные переводы", "Кассовые документы", "Кассы", "Конвертация валют", "Кассы"],
        "path": "anor/mkcs/cashbox_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Денежные переводы", "Кассовые документы", "Конвертация валют"],
        "path": "anor/mkcs/exchange_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Денежные переводы", "Кассовые документы", "Денежные переводы"],
        "path": "anor/mkcs/transfer_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Денежные переводы", "Кассовые документы", "Статьи доходов"],
        "path": "anor/mkr/income_article_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Денежные переводы", "Кассовые документы", "Статьи расходов"],
        "path": "anor/mkr/expense_article_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Денежные переводы", "Кассовые документы", "Переоценки валют"],
        "path": "anor/mku/revaluation_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Денежные переводы", "Конвертация валют"],
        "path": "anor/mkcs/exchange_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Денежные переводы", "Кассы"],
        "path": "anor/mkcs/cashbox_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Банковские выписки",
        "page_links": ["Конвертации расчетных счетов (Бета)"],
        "path": "anor/mkcs/bank_exchange_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Уставный капитал",
        "page_links": ["Дивиденды"],
        "path": "anor/mku/profit_share/profit_share_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Уставный капитал",
        "page_links": ["Дивиденды", "Уставный капитал"],
        "path": "anor/mku/authorized_capital/authorized_capital_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Уставный капитал",
        "page_links": ["Дивиденды", "Закрытие периода"],
        "path": "anor/mku/close_period/close_period_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Уставный капитал",
        "page_links": ["Дивиденды", "Закрытие периода", "Счета закрытия периода"],
        "path": "anor/mku/close_period/close_period_coa_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Уставный капитал",
        "page_links": ["Дивиденды", "Закрытие периода", "Дивиденды"],
        "path": "anor/mku/profit_share/profit_share_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Уставный капитал",
        "page_links": ["Закрытие периода"],
        "path": "anor/mku/close_period/close_period_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Уставный капитал",
        "page_links": ["Счета закрытия периода"],
        "path": "anor/mku/close_period/close_period_coa_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Взаиморасчеты",
        "page_links": ["Парные счета"],
        "path": "anor/mku/coa_twin_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Взаиморасчеты",
        "page_links": ["Парные счета", "Взаиморасчеты"],
        "path": "anor/mku/offset/offset_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Перекидка аванса клиентов / поставщиков",
        "page_links": ["Статьи доходов"],
        "path": "anor/mkr/income_article_list",
    },
    {
        "menu_column": "Основное",
        "menu_item": "Перекидка аванса клиентов / поставщиков",
        "page_links": ["Статьи расходов"],
        "path": "anor/mkr/expense_article_list",
    },
    {
        "menu_column": "Денежный поток",
        "menu_item": "Мои заявки",
        "page_links": ["Шаблоны документооборота"],
        "path": "anor/mkcs/request/sign_template_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Валюты",
        "page_links": ["Конвертация валют"],
        "path": "anor/mkcs/exchange_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Валюты",
        "page_links": ["Конвертация валют", "Кассовые документы"],
        "path": "anor/mkcs/cash/operation_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Валюты",
        "page_links": ["Конвертация валют", "Кассовые документы", "Кассы"],
        "path": "anor/mkcs/cashbox_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Валюты",
        "page_links": ["Конвертация валют", "Кассовые документы", "Кассы", "Кассовые документы"],
        "path": "anor/mkcs/cash/operation_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Валюты",
        "page_links": ["Конвертация валют", "Кассовые документы", "Кассы", "Денежные переводы"],
        "path": "anor/mkcs/transfer_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Валюты",
        "page_links": ["Конвертация валют", "Кассовые документы", "Кассы", "Денежные переводы", "Кассовые документы"],
        "path": "anor/mkcs/cash/operation_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Валюты",
        "page_links": ["Конвертация валют", "Кассовые документы", "Кассы", "Денежные переводы", "Конвертация валют"],
        "path": "anor/mkcs/exchange_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Валюты",
        "page_links": ["Конвертация валют", "Кассовые документы", "Кассы", "Денежные переводы", "Кассы"],
        "path": "anor/mkcs/cashbox_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Валюты",
        "page_links": ["Конвертация валют", "Кассовые документы", "Кассы", "Конвертация валют"],
        "path": "anor/mkcs/exchange_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Валюты",
        "page_links": ["Конвертация валют", "Кассовые документы", "Конвертация валют"],
        "path": "anor/mkcs/exchange_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Валюты",
        "page_links": ["Конвертация валют", "Кассовые документы", "Денежные переводы"],
        "path": "anor/mkcs/transfer_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Валюты",
        "page_links": ["Конвертация валют", "Кассовые документы", "Статьи доходов"],
        "path": "anor/mkr/income_article_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Валюты",
        "page_links": ["Конвертация валют", "Кассовые документы", "Статьи расходов"],
        "path": "anor/mkr/expense_article_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Валюты",
        "page_links": ["Конвертация валют", "Кассовые документы", "Переоценки валют"],
        "path": "anor/mku/revaluation_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Валюты",
        "page_links": ["Конвертация валют", "Денежные переводы"],
        "path": "anor/mkcs/transfer_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Валюты",
        "page_links": ["Конвертация валют", "Кассы"],
        "path": "anor/mkcs/cashbox_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "План счетов",
        "page_links": ["План главных счетов"],
        "path": "anor/mk/coa_group_list",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "План счетов",
        "page_links": ["Настройки счетов"],
        "path": "anor/mk/default_coa_setting",
    },
    {
        "menu_column": "Справочники",
        "menu_item": "Договоры",
        "page_links": ["Дополнительные договоры"],
        "path": "anor/mkf/sub_contract_list",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Акт-сверки",
        "page_links": ["Настройка счетов акта-сверки"],
        "path": "anor/rep/mkr/reconciliation_acts_coa_setting",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Прибыль и убыток (PnL)",
        "page_links": ["Настройка прибыли и убытков"],
        "path": "anor/mkr/profit_and_loss_setting",
    },
    {
        "menu_column": "Отчеты",
        "menu_item": "Отчет о прибылях и убытках (БЕТА)",
        "page_links": ["Настройка плана счетов прибыли и убытков"],
        "path": "anor/mku/pnl_setting",
    },
]


FORM_BUCKETS = (
    {
        "forms": [*OPERATIONAL_DIRECT_FORMS, *OPERATIONAL_PAGE_LINK_FORMS],
        "filial": OPERATIONAL_PLACEHOLDER,
        "section": "operational",
    },
)
